# Iris classification

- One - hot encoding
- Softmax
- crossentropy loss function

In [ ]:
import pandas as pd
import tensorflow as tf
print(tf.__version__)

2.3.0


In [ ]:
# Data
Path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
Iris = pd.read_csv(Path)
Iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
# one - hot encoding
Iris = pd.get_dummies(Iris)
Iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [15]:
# X,Y for training
x_train = Iris[["꽃잎길이" ,"꽃잎폭", "꽃받침길이", "꽃받침폭"]]
y_train = Iris[["품종_setosa",	"품종_versicolor",	"품종_virginica"]]
print(x_train.shape, y_train.shape)

(150, 4) (150, 3)


In [17]:
X = tf.keras.layers.Input(shape=[4])   # count of feature
y = tf.keras.layers.Dense(3,activation='softmax')(X)
model = tf.keras.models.Model(X,y)
model.compile(loss = 'categorical_crossentropy',metrics='accuracy')

In [18]:
# model fit
model.fit(x_train, y_train,epochs=1000,verbose=0)
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1632 - accuracy: 0.9667
Epoch 2/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1633 - accuracy: 0.9667
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1635 - accuracy: 0.9600
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1630 - accuracy: 0.9667
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1628 - accuracy: 0.9667
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1626 - accuracy: 0.9667
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1625 - accuracy: 0.9667
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1625 - accuracy: 0.9667
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1624 - accuracy: 0.9600
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1623 - accuracy: 0.9600


In [22]:
# test
print(model.predict(x_train[-5:]))
print(y_train[-5:])
print(model.weights)

[[7.9803931e-07 7.2777316e-02 9.2722189e-01]
 [1.3881488e-06 1.5876763e-01 8.4123099e-01]
 [3.5769103e-06 1.9377689e-01 8.0621958e-01]
 [1.5000592e-06 7.8882165e-02 9.2111629e-01]
 [1.0445343e-05 2.9176241e-01 7.0822710e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1
[<tf.Variable 'dense_2/kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.15346096,  0.07777529, -0.5368572 ],
       [ 3.708863  ,  0.48513293, -0.89884657],
       [-3.4643066 ,  0.04117777,  0.8367681 ],
       [-4.0268917 , -2.2404556 ,  1.8997657 ]], dtype=float32)>, <tf.Variable 'dense_2/bias:0' shape=(3,) dtype=float32, numpy=array([ 1.986153 ,  1.2478727, -1.5969411], dtype=float32)>]
